<?php

//Define the texts for reviewer help
//These texts will be displayed above the review comments box.

define ( 'FULL_PAPER' , 'This manuscript was submitted as \'full paper\' and should be reviewed along the usual dimensions for research contributions which include (1) originality, (2) significance of the results, and (3) quality of writing.' );
  define ( 'SURVEY_ARTICLE' , 'This manuscript was submitted as \'Survey Article\' and should be reviewed along the following dimensions: (1) Suitability as introductory text, targeted at researchers, PhD students, or practitioners, to get started on the covered topic. (2) How comprehensive and how balanced is the presentation and coverage. (3) Readability and clarity of the presentation. (4) Importance of the covered material to the broader Semantic Web community.' );
define ( 'DATA_DESCRIPTION' , 'This manuscript was submitted as \'Data Description\' and should be reviewed along the following dimensions: (1) Quality of the dataset. (2) Usefulness (or potential usefulness) of the dataset. (3) Clarity and completeness of the descriptions.' );
define ( 'ONTOLOGY_DESCRIPTION' , 'This manuscript was submitted as \'Ontology Description\' and should be reviewed along the following dimensions:  (1) Quality and relevance of the described ontology (convincing evidence must be provided). (2) Illustration, clarity and readability of the describing paper, which shall convey to the reader the key aspects of the described ontology.' );
define ( 'APPLICATION_REPORT' , 'This manuscript was submitted as \'Application Report\' and should be reviewed along the following dimensions: (1) Quality, importance, and impact of the described application (convincing evidence must be provided). (2) Clarity and readability of the describing paper, which shall convey to the reader the key ideas regarding the application of Semantic Web technologies in the application.' );
define ( 'TOOLS_SYSTEMS', 'This manuscript was submitted as \'Tools and Systems Report\' and should be reviewed along the following dimensions: (1) Quality, importance, and impact of the described tool or system (convincing evidence must be provided). (2) Clarity, illustration, and readability of the describing paper, which shall convey to the reader both the capabilities and the limitations of the tool.' );

